upstream discovery-ai-backend {
    server discovery-ai-backend:3000;
}

upstream discovery-ai-frontend {
    server discovery-ai-frontend:3456;
}

server {
    listen 8081;

    client_max_body_size 10M;

    location /api/ {
        proxy_pass http://discovery-ai-backend/;

        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://discovery-ai-frontend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}